#!/bin/sh -e

docker build -t img_imc .
docker run --name imc img_imc bash -c "scrapy crawl google -L INFO -a max_count=100 -a \"key=$1\""
rm -rf ./output
docker cp imc:/scrapy/ImStore/full ./output
docker rm imc
